<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.shubham</groupId>
    <artifactId>AssetManagementSystem</artifactId>
    <version>1.0</version>

    <packaging>war</packaging>

    <dependencies>

        <!-- Servlet API -->
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>4.0.1</version>
            <scope>provided</scope>
        </dependency>

        <!-- MySQL JDBC -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.33</version>
        </dependency>
        
        	<dependency>
			    <groupId>com.heroku</groupId>
			    <artifactId>webapp-runner</artifactId>
			    <version>10.1.20.0</version>
			    <scope>provided</scope>
			</dependency>

    </dependencies>

    <build>

        <finalName>ROOT</finalName>

        <plugins>

            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.3.2</version>
            </plugin>

        </plugins>

    </build>
    
    <build>
    <finalName>AssetManagementSystem</finalName>

    <plugins>

        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>3.6.1</version>

            <executions>
                <execution>
                    <id>copy</id>
                    <phase>package</phase>

                    <goals>
                        <goal>copy</goal>
                    </goals>

                    <configuration>

                        <artifactItems>

                            <artifactItem>

                                <groupId>com.heroku</groupId>

                                <artifactId>webapp-runner</artifactId>

                                <version>10.1.20.0</version>

                                <destFileName>
                                    webapp-runner.jar
                                </destFileName>

                            </artifactItem>

                        </artifactItems>

                        <outputDirectory>
                            ${project.build.directory}/dependency
                        </outputDirectory>

                    </configuration>

                </execution>

            </executions>

        </plugin>

    </plugins>

</build>
    

</project>